### ISSUE TITLE
Cannot save with Save buttons

### ISSUE THREAD

**Issue by wadiv76** [mcserversoft/IssueTracker#1]
**Describe the bug**
Under scheduler when editing any of the tasks and I hit save nothing is saved

**To Reproduce**
1. Go to Scheduler
2. Click on existing schedule edit pencil button
3. Modify a setting like Enabled and click Save

**Expected behavior**
When hitting save the button should be depressed to indicate something has happened and the window should probably close

**Desktop (please complete the following information):**
 - OS: Windows 10
- MCSS Version 12.7.0

**Comment by Fiahblade** [comment]
@wadiv76 Hi, thank you for reporting this issue. Does this still affect v13?

**Comment by wadiv76** [comment]
No! Thank you! The new design is amazing! The save buttons work.  I did notice, and I can create a new issue if you would like, that when enabling/disabling through these Pencil | Create Task edit window that the time is wiped out and set to 00:00:00.  Easy work around is to set the time again

**Comment by Fiahblade** [comment]
@wadiv76 Good to hear that. I also spotted the 00:00:00 issue, will be fixed next. You don't need to create a new issue but please do next time ;)

**Comment by Fiahblade** [comment]
Has been fixed, will be included in the next update. Thanks!
