### ISSUE TITLE
Usage of public APIs 

### ISSUE THREAD

**Issue by Dobby-progam** [mcserversoft/IssueTracker#8]
**Is your feature request related to a problem? Please describe.**
When I first launch the software I was impressed by how good it looks, but I miss a thing and that mainly involves the usege of api's to download mods, plugins and server software.

**Describe the solution you'd like**
I hope to see in a update that it could be added that you can make a request, an can download mods plugins ect
**Describe alternatives you've considered**
I don't really have a other solution for this right now 

**Additional context**

**Comment by PouletteMC** [comment]
Answered on discord
